instrumentation:
    include-all-sources: true
    excludes:
        - benchmarks/**
        - thrift-idl.js
        - thrift2json.js
        - browser/**
check:
    global:
        statements: 95
        lines: 95
        branches: 95
        functions: 95
    each:
        statements: 95
        lines: 95
        branches: 95
        functions: 95
